### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by n-aggarwal** [ananafrida/comp-333-4-frontend#10]
Deadline: 11/14 5:00pm

**Comment by ananafrida** [comment]
Team Task Rules:

1. Required PR review within 24 hours
2. Required response to comments within 24 hours
3. Required task completion within the deadlines mentioned in respective tickets. Otherwise, the other person takes it

**Comment by ananafrida** [comment]
- [x] "For any outside resource that you use, please include a link to it in your code or in your readme, whichever is more appropriate."

**Comment by ananafrida** [comment]
@n-aggarwal one last thing, could you comment your code sufficiently?

**Comment by ananafrida** [comment]
Since you didn't comment on your code, I had to do it. Couldn't wait for the last hour since I needed to sleep.
