### ISSUE TITLE
Add update functionality

### ISSUE THREAD

**Issue by ananafrida** [ananafrida/comp-333-4-frontend#8]

**Comment by ananafrida** [comment]
11/14 -- 5pm

**Comment by ananafrida** [comment]
@n-aggarwal it has been over 24 hours but still my PRs are not reviewed for either update or delete tickets even though we set the team rule to review PRs within 24 hours. I can't implement search without these merging since there are some dependencies. You are violating our team rules.

**Comment by n-aggarwal** [comment]
@ananafrida We did not set any such rules when we met, and you didn't communicate about them at all. Next time, please make sure to communicate your team expectations ahead of time.

**Comment by ananafrida** [comment]
We did decide and communicate each rule clearly during our meeting.

**Comment by n-aggarwal** [comment]
Then I must have Alzheimer's or something, because I have no recollection of that.

**Comment by n-aggarwal** [comment]
Since the star rating is fixed, I am closing the issue.
