### ISSUE TITLE
Add create functionality

### ISSUE THREAD

**Issue by ananafrida** [ananafrida/comp-333-4-frontend#9]

**Comment by n-aggarwal** [comment]
Deadline: November 14, 5:00 pm

**Comment by ananafrida** [comment]
FYI, "Your frontend should make use of icons for star ratings". Haven't looked into the PR yet but just to emphasize add ratings as stars, not numbers. There are extra points for this task.

**Comment by n-aggarwal** [comment]
I am taking input as a number, when creating but displaying as stars on my read screen. Are you positive that we need to "create" rating as star rating? If so, could you please quote the sentence.

**Comment by ananafrida** [comment]
>  Your frontend should make use of icons for star ratings

Acknowledged. I believe as long as you have star icons somewhere (create or read), we are safe.

**Comment by ananafrida** [comment]
@n-aggarwal purpose of reopening the issue:
 The rating field allows users to input any value. Could you please fix that? It should be a quick regex fix like I did in my update func code below.
```
// Validate rating: must be between 1 and 5
    const isValidRating = /^[1-5]$/.test(rating);

    if (!isValidRating) {
      // Display an error message or take appropriate action for an invalid rating
      console.error("Invalid rating. Please enter a number between 1 and 5.");
      return;
    }
```

**Comment by ananafrida** [comment]
@n-aggarwal I just came out of the TA session. The TA said we have to have stars as a rating instead of numbers in the input field. Could you fix that or I can do it too. Please lmk asap.

**Comment by n-aggarwal** [comment]
Sorry for the delay, I was in a class, and wasn't able to respond. I will be free at around 11:00 pm at which time, I will work on it at that time.

**Comment by ananafrida** [comment]
@n-aggarwal the create doesn't handle it. PLEASE FIX IT.

> A user should be only able to rate (i.e, create) a particular song once. A user should be notified that 
they cannot rate (i.e., create) a song twice if they try

**Comment by n-aggarwal** [comment]
Double check your params. The check for that is done on the backend.
